import type { HtaMonth } from '../types'
import { formatNumber, performancePercent } from '../lib/utils'

type Props = { months: HtaMonth[] }
export function KpiCards({ months }: Props) {
  const reach = months.reduce((sum, item) => sum + (item.reach ?? 0), 0); const target = months.reduce((sum, item) => sum + (item.target ?? 0), 0); const percent = performancePercent(reach, target); const onTarget = months.filter((item) => performancePercent(item.reach, item.target) >= 100).length; const tests = months.reduce((sum, item) => sum + (item.hivTests ?? 0), 0); const sti = months.reduce((sum, item) => sum + (item.stiTreated ?? 0), 0); const male = months.reduce((sum, item) => sum + (item.condomsMale ?? 0), 0); const female = months.reduce((sum, item) => sum + (item.condomsFemale ?? 0), 0); const outreach = months.reduce((sum, item) => sum + (item.outreaches ?? 0), 0); const groups = months.reduce((sum, item) => sum + (item.supportGroups ?? 0), 0)
  const tone = percent >= 100 ? 'green' : percent >= 80 ? 'amber' : 'red'
  return <section className="kpi-grid"><article className={`hero-kpi ${tone}`}><p>Performance vs target</p><strong>{percent}%</strong><span>{formatNumber(reach)} of {formatNumber(target)} clients reached</span><div className="progress"><i style={{ width: `${Math.min(percent, 100)}%` }} /></div></article><article className="stat-card"><span>Clients reached / target</span><strong>{formatNumber(reach)} <em>/ {formatNumber(target)}</em></strong></article><article className="stat-card"><span>Months on target</span><strong>{onTarget} <em>/ {months.length}</em></strong></article><article className="stat-card"><span># HIV tests <b className="uncaptured">{months.filter((item) => item.hivTests === null).length} uncaptured</b></span><strong>{formatNumber(tests)}</strong></article><article className="stat-card"><span># STI treated</span><strong>{formatNumber(sti)}</strong></article><article className="stat-card"><span>Condoms distributed</span><strong>{formatNumber(male + female)}</strong><small>{formatNumber(male)} male / {formatNumber(female)} female</small></article><article className="stat-card"><span>Programmes held</span><strong>{formatNumber(outreach + groups)}</strong><small>{formatNumber(outreach)} outreaches / {formatNumber(groups)} groups</small></article></section>
}
