import { FormEvent, useEffect, useState } from 'react'
import type { HtaMonth, HtaMonthInput } from '../types'

type Props = { month: HtaMonth | null; onClose: () => void; onSave: (data: HtaMonthInput) => Promise<void>; onDelete: (id: string) => Promise<void> }
type FormData = Omit<HtaMonth, 'updatedAt'>
const blank: FormData = { id: '', year: 2026, month: 3, reach: null, target: 340, hivTests: null, stiTreated: null, condomsMale: 42000, condomsFemale: 1500, outreaches: null, supportGroups: null, note: null }
export function MonthModal({ month, onClose, onSave, onDelete }: Props) { const [form, setForm] = useState<FormData>(month ?? blank); const [busy, setBusy] = useState(false); useEffect(() => setForm(month ?? blank), [month]); const set = (key: keyof FormData, value: string) => setForm((current) => ({ ...current, [key]: ['year', 'month'].includes(key) ? Number(value) : ['reach', 'target', 'hivTests', 'stiTreated', 'condomsMale', 'condomsFemale', 'outreaches', 'supportGroups'].includes(key) ? (value === '' ? null : Number(value)) : value }))
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); await onSave({ ...form, id: form.id || `${form.year}-${String(form.month + 1).padStart(2, '0')}` }); setBusy(false); onClose() }
  const numberField = (key: keyof FormData, label: string) => <label>{label}<input type="number" min="0" value={(form[key] as number | null) ?? ''} onChange={(e) => set(key, e.target.value)} /></label>
  return <div className="modal-backdrop" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><form className="modal" onSubmit={submit}><div className="modal-heading"><div><p className="eyebrow">{month ? 'EDIT MONTH' : 'NEW MONTH'}</p><h2>{month ? month.id : 'Add programme month'}</h2></div><button type="button" className="close-button" onClick={onClose}>Close</button></div>{!month && <div className="field-row"><label>Year<input type="number" value={form.year} onChange={(e) => set('year', e.target.value)} /></label><label>Month<select value={form.month} onChange={(e) => set('month', e.target.value)}>{Array.from({ length: 12 }, (_, index) => <option key={index} value={index}>{new Date(2026, index, 1).toLocaleString('en', { month: 'long' })}</option>)}</select></label></div>}<fieldset><legend>Client reach</legend><div className="field-row">{numberField('reach', 'Reach')}{numberField('target', 'Target')}</div></fieldset><fieldset><legend>Testing & treatment</legend><div className="field-row">{numberField('hivTests', 'HIV tests')}{numberField('stiTreated', 'STI treated')}</div></fieldset><fieldset><legend>Condom distribution</legend><div className="field-row">{numberField('condomsMale', 'Male condoms')}{numberField('condomsFemale', 'Female condoms')}</div></fieldset><fieldset><legend>Programmes</legend><div className="field-row">{numberField('outreaches', 'Outreaches')}{numberField('supportGroups', 'Support groups')}</div></fieldset><label>Note<textarea value={form.note ?? ''} onChange={(e) => set('note', e.target.value)} rows={3} /></label><div className="modal-actions">{month && <button type="button" className="delete-button" onClick={async () => { await onDelete(month.id); onClose() }}>Delete</button>}<span /><button type="button" className="outline-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={busy}>{busy ? 'Saving...' : 'Save month'}</button></div></form></div>
}
